# Files that determines the type of its parent directory
TYPICAL_FILES = {
"code": set([
    r'^\.git$',
    r'^\.hg$',
    r'^\.svn$',
    r'^\.bzr$',
    r'^\.gitignore$',
    r'^\.gitattributes$',
    r'^\.hgignore$',
    r'^\.npmignore$',
    r'^\.dockerignore$',
    r'^package\.json$',
    r'^yarn\.lock$',
    r'^Gemfile$',
    r'^Gemfile\.lock$',
    r'^Pipfile$',
    r'^Pipfile\.lock$',
    r'^requirements\.txt$',
    r'^go\.mod$',
    r'^go\.sum$',
    r'^Cargo\.toml$',
    r'^Cargo\.lock$',
    r'^composer\.json$',
    r'^composer\.lock$',
    r'^.*csproj$',
    r'^.*fsproj$',
    r'^.*vbproj$',
    r'^gradlew$',
    r'^gradlew\.bat$',
    r'^build\.gradle$',
    r'^pom\.xml$',
    r'^Makefile$',
    r'^CMakeLists\.txt$',
    r'^setup\.py$',
    r'^Rakefile$',
    r'^Gruntfile\.js$',
    r'^gulpfile\.js$',
    r'^webpack\.config\.js$',
    r'^rollup\.config\.js$',
    r'^\.travis\.yml$',
    r'^\.circleci$',
    r'^\.github$',
    r'^Dockerfile$',
    r'^Vagrantfile$',
    r'^\.env$',
    r'^\.editorconfig$',
    r'^\.prettierrc$',
    r'^\.eslintrc$',
    r'^tsconfig\.json$',
    r'^\.vscode$',
    r'^.*\.tex$',
    r'README(\.md)?$',
    r'^LICENSE$',
]), 
"game": set([
    r'^Game.exe$', # RPG Maker, or Wolf
    r'^.*\.xp3$', # KiriKiri
    r'^Game.rgss3a$', # RPG Maker
    r'^BGI.exe$', # BGI
    r'^.*\.arc$', # also BGI
    r'^save$',  # some text games with local saves
    r'^savedata$', # ditto
    r'^.*\.dat$', 
    r'^.*\.sav$',
    r'^.*\.rpgsave$',
    r'^.*\.mpk$',
    r'^.*\.pak$', # some kirikiri games
    r'^Ron2.exe$', # RON
    r'^.*\.rpyc$', # Ren'Py
    r'^renpy$', # ditto
    r'^tyrano$', # TyranoScript
    r'^UnityPlayer.dll$', # Unity
    r'^BGM$', # some games, like CrackleCradle
    r'^root\.pfs', # Artemis Engine
    r'^.*_Data$', # Unity
    r'^README\.txt$', # some games
]), 
"software": set([
    r'^.*\.dll$',
    r'^Unins\w*\.exe$',
]), 
"album": set([
    r'^.*\.cue$',
]),
}

EXTENSIONS = {
    "image": set((
        "jpg",
        "png",
        "jpeg",
        "gif",
        "bmp",
        "svg",
        "webp",
        "ico",
        "tif",
        "tiff",
        "psd",
        "ai",
        "eps",
        "indd",
        "raw",
        "cr2",
        "nef",
        "orf",
        "sr2",
        "heif",
        "dwg",
        "dxf",
        "3ds",
        "skp",
        "ps",
        "xcf",
    )),
    "video": set((
        "mp4",
        "mov",
        "avi",
        "wmv",
        "flv",
        "webm",
        "mkv",
        "vob",
        "ogv",
        "drc",
        "gifv",
        "mng",
        "qt",
        "yuv",
        "rm",
        "rmvb",
        "asf",
        "amv",
        "m4p",
        "m4v",
        "mpg",
        "mp2",
        "mpeg",
        "mpe",
        "mpv",
        "m2v",
        "svi",
        "3gp",
        "3g2",
        "mxf",
        "roq",
        "nsv",
    )),
    "audio": set((
        "mp3",
        "wav",
        "flac",
        "aac",
        "ogg",
        "wma",
        "m4a",
        "m4p",
        "m4b",
        "m4r",
        "3gp",
        "amr",
        "mid",
        "midi",
        "imy",
    )),
    "document": set((
        "doc",
        "docx",
        "xls",
        "xlsx",
        "ppt",
        "pptx",
        "pdf",
        "odt",
        "ods",
        "odp",
        "odg",
        "odf",
        "txt",
        "rtf",
        "tex",
        "wks",
        "wps",
        "wpd",
    )),
    "source_file": set((
        "py",
        "c",
        "cpp",
        "h",
        "hpp",
        "cs",
        "java",
        "js",
        "ts",
        "tsx",
        "jsx",
        "go",
        "rs",
        "rb",
        "php",
        "sh",
        "bat",
        "ps1",
        "swift",
        "kt",
        "ktm",
        "kts",
        "clj",
        "cljs",
        "cljc",
        "groovy",
        "scala",
        "sc",
        "lua",
        "dart",
        "coffee",
        "elm",
        "erl",
        "ex",
        "exs",
        "f",
        "f90",
        "f95",
        "f03",
        "f08",
        "fs",
        "fsi",
        "fsx",
        "ml",
        "mli",
        "mll",
        "mly",
        "nim",
        "r",
        "nb"
    )),
}

FILENAME_PATTERNS : list[tuple[str | list[str], str] ]= [
    # ArXiv paper
    ("arxiv", r'^\d{4}\.\d{4,5}\.pdf$'),
    
    # Game Software
    (["game", "dmm"], r'^[a-z]{4,5}_\d{4,5}\.exe$'),
    
    # Media Software
    (["media", "DLsite"], r'^(RJ|VJ)\d{6,8}\.zip$'),
    
    # Book
    (["book", "DLsite"], r'^BJ\d{6,8}\.zip$'),
]